### ISSUE TITLE
Infoboxen layout

### ISSUE THREAD

**Issue by abilustue** [Tuepedia/Skinopt#1]
beim  Chameleon-Skin verändert es das Aussehen der Infoboxen-Vorlagen, zb Infobox Ort, aber auch Geschäft: Das Wappen ist nicht mehr mittig, es geht etwas an Raum verloren zwischen den Angaben etc.

mit Vector sieht es so aus, meiner Meinung nach ok, eleganter geht immer :-)
![grafik](https://user-images.githubusercontent.com/43342934/45628057-876fa580-ba93-11e8-9863-97e58170053d.png)

Mit chameleon kommt es so raus:
![grafik 1](https://user-images.githubusercontent.com/43342934/45628072-8cccf000-ba93-11e8-90ab-c6365adf952d.png)

**Comment by Till-Kopper** [comment]
Da muss man für die Tabelle einen Margin definieren, dann sind die Texte nicht immer press an den Tabellenlinien.
Und für das erste Tabellenfeld (das über zwei Kolumnen geht), eine Mittelausrichtung. Das "Pfrondorf" im unteren Bespiel ist ja auch schon schön mittig.

**Comment by dktue** [comment]
Es muss ein `padding` für die Zellen definiert werden (kein `margin`).

**Comment by abilustue** [comment]
Die Frage ist eben, wo dieses CSS am besten hinkommt, damit es wirkt. Da es bei Vector funktioniert kann ich da mal schauen, wie es aussieht. 
Welche Datei wäre denn die geeignete, damit es bei chameleon ankommt?

**Comment by dktue** [comment]
Behoben in der Vorlage selbst

![image](https://user-images.githubusercontent.com/2878623/45781622-cb63d580-bc60-11e8-9fb4-d0b519b335f9.png)
