### ISSUE TITLE
Logo-Darstellung Verbessern

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#10]
Die Darstellung des Logos im Chameleon-Skin soll verbessert werden:
![image](https://user-images.githubusercontent.com/2878623/45944996-55f35e80-bfec-11e8-8f5f-46eb4dc2db96.png)

**Comment by dktue** [comment]
Ich habe ein wenig experimentiert, allerdings komme ich immer zum Schluss, dass der Platz so eng ist, dass man den Untertitel des Logos nicht sinnvoll abbilden kann.

Wollen wir ihn (an dieser Stelle) komplett streichen? Ein vergrößern der ohnehin schon großen Navigationsleiste halte ich nicht für verhältnismäßig.

**Comment by abilustue** [comment]
Kann man denn einstellen: hier nehme Logo 1 (mit Text), hier nehme Logo 2 (ohne Text) - oder kann man im Hintergrund die verschiedenen Größen-jpgs (oder gif, png etc) editieren? WEnn du magst, Daniel, kannst du ja mal mit dem Logo experimentieren, es ist einfach über die TÜpedia zugänglich (https://www.tuepedia.de/wiki/Datei:Logo_1365.jpg) - Danke&Grüße

**Comment by Till-Kopper** [comment]
Das Logo sollte in irgendeiner Form auf jeden Fall dableiben. Man muss es ja nicht lesen können. Aber das man es wiederkennen kann.

**Comment by dktue** [comment]
@Till-Kopper : Bist Du der Meinung, dass es in der jetzigen Größe wiedererkennbar ist?

**Comment by Till-Kopper** [comment]
@dktue : ja. Und nebenbei: das Github-Logo hier oben links ist auch nicht wesentlich größer. Und ich kann hier am Desktop und Mobil das TÜpedia Logo durchaus lesen.

**Comment by dktue** [comment]
:raised_hand: vote für **Close**
