### ISSUE TITLE
<htmltag tagname="a"> ist nicht erlaubt

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#13]
Wird in einer Seite `<htmltag tagname="a">` verwendet, so führt die zu folgender Meldung:

> Der Tagname „a“ wird von <htmltag> nicht unterstützt.

**Comment by abilustue** [comment]
WElche Attribute bräuchtest du denn zu <a> ? 
https://www.mediawiki.org/wiki/Extension:HTML_Tags

**Comment by dktue** [comment]
Das Attribut `href` würde ich benötigen.

**Comment by abilustue** [comment]
ich hab es eingebaut im Wiki, müsste jetzt gehen

**Comment by dktue** [comment]
Funktioniert, danke!
