### ISSUE TITLE
Probleme bei der mobilen Darstellung 

### ISSUE THREAD

**Issue by abilustue** [Tuepedia/Skinopt#14]
User-feedback: Bei mir am Smartphone (Sony experia - eher kleiner Bildschirm) werden die Bilder in einem Artikel in fixer Größe angezeigt so dass ich nur einen Ausschnitt sehe, ich kann sie nur mit dem medienbetrachter öffnen und dann verkleinern. Fühlt sich etwas sperrig und unflexibel an. Das Titelbild zb bei Hans herb ist der Bildschirmgröße angepasst, die anderen nicht.

**Comment by dktue** [comment]
Habe ein wenig CSS angepasst -- bitte nochmal testen.

**Comment by abilustue** [comment]
Jetzt ist es besser! Danke
