### ISSUE TITLE
Poem-Erweiterung aktivieren

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#15]
Die [Poem-Erweiterung](https://www.mediawiki.org/wiki/Extension:Poem) scheint nicht aktiviert zu sein, siehe [Ginkgo](https://www.tuepedia.de/wiki/Ginkgo).

**Comment by abilustue** [comment]
Ich schaue demnächst danach, müsste leicht gehen.

**Comment by abilustue** [comment]
hab die Poem-extension installiert und aktiviert

**Comment by dktue** [comment]
Funktioniert, danke!
