### ISSUE TITLE
Umstellen auf neue Startseite

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#22]
Die Startseite soll den Inhalt von _Neue Startseite mit Templates_ erhalten.

**Comment by abilustue** [comment]
Ich stelle es heute abend noch um.

**Comment by abilustue** [comment]
Es ist umgestellt.

**Comment by abilustue** [comment]
Danke für die viele Arbeit 
![grafik](https://user-images.githubusercontent.com/43342934/46977213-d9740d00-d0cb-11e8-9371-f0bc59a7d156.png)
