### ISSUE TITLE
Artikel-Bilderwunsch-Seite aktualisiert nicht

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#23]
Die [Artikel-Bilderwunsch-Seite](https://www.tuepedia.de/wiki/Kategorie:T%C3%9Cpedia:Artikel-Bilderwunsch) aktualisiert anscheinend nicht mehr.

**Comment by buckalot** [comment]
Fixed. Sollte ab morgen wieder normal laufen.

Der Cronjob ist wohl seit dem letzten Update nicht richtig gelaufen. Sollte jetzt aber auch wieder stabil laufen.
