### ISSUE TITLE
Erweiterung External Data installieren

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#25]
Ich möchte gerne externe Daten verknüpfen und benötige hierfür die Erweiterung [External Data](https://www.mediawiki.org/wiki/Extension:External_Data).

**Comment by abilustue** [comment]
Ist installiert - wenn ich noch irgendwelche Opotionen einstellen soll, gib Bescheid.

**Comment by dktue** [comment]
Funktioniert, danke!
