### ISSUE TITLE
TÜpedia-Alphabet

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#26]
Ich möchte gerne zur Diskussion stellen den Menüpunkt "TÜpedia-Alphabet" zu entfernen.

Persönlich nutze ich diese Funktion nicht und ich wüsste auch nicht, welcher Anwendungsfall hier abgedeckt werden könnte. Stöbern geht über die Portale besser, finden über die Suche.

Ich freue mich über Eure Meinungen.

**Comment by abilustue** [comment]
Ich kann nicht mehr genau sagen, woher das stammt. Ich selbst nutze es auch nicht. Aber es könnte sein, dass zb Nutzer hubertq da dran interessiert ist, insofern fände ich es eigentlich gut, einen Ort in der TÜpedia für die Diskussion zu finden.

**Comment by dktue** [comment]
Guter Punkt -- ich habe es auf die dortige [Diskussionsseite](https://www.tuepedia.de/wiki/Diskussion:T%C3%BCpedia-Alphabet) verlagert und schlage ein zweiwöchiges Moratorium vor.
