### ISSUE TITLE
Installation der Erweiterung StringFunctions

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#27]
Für Vorlagen wäre die Erweiterung [StringFunctions](https://www.mediawiki.org/wiki/Extension:StringFunctions/de) nützlich.

**Comment by abilustue** [comment]
Die Erweiterung scheint es nicht mehr zu geben (zum download etc). Ich habe den folgenden Tipp genutzt und die Stringfunktionen der Parserfunctions über die Localsettings aktiviert. 

Von der Seite https://www.mediawiki.org/wiki/Extension:StringFunctions/de

Hinweis: | All diese Funktionen außer #pad, #urldecode und #urlencode wurden in die Erweiterung ParserFunctions in der Version r50997 integriert.  Diese Version ist für MediaWiki 1.16 erstellt worden, auf früheren  Versionen könnte ein Update auf die Stammversion funktionieren.
-- | --

**Comment by abilustue** [comment]
Um diese Funktionen in der Erweiterung ParserFunctions (Version r50997) zu nutzen, musst du in der LocalSettings.php "$wgPFEnableStringFunctions = true;" setzen

**Comment by dktue** [comment]
Funktioniert, danke!
