### ISSUE TITLE
Einstellung für nicht gesetzte Variablen in ExternalData-Extension ändern

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#29]
Die Einstellung für die Fehler-Anzeige bei nicht gesetzten Variablen soll deaktiviert werden [(Dokumentation)](https://www.mediawiki.org/wiki/Extension:External_Data#Displaying_individual_values).
`$edgExternalValueVerbose = false;`

**Comment by Till-Kopper** [comment]
Habe ich in der Datei LocalSettings.php der Version 1.31.0 auf dem Server geändert. Ist damit erledigt.

**Comment by dktue** [comment]
Gut zu wissen, dass Du das auch ändern kannst @Till-Kopper . ;)

**Comment by abilustue** [comment]
Danke, Till 👍
