### ISSUE TITLE
Installieren der Erweiterung Arrays

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#32]
Ich würde gerne die Erweiterung [Arrays](https://www.mediawiki.org/wiki/Extension:Arrays) nutzen.

**Comment by dktue** [comment]
Damit wäre es möglich, die Buslinien aus OSM direkt auf Artikel in TÜpedia zu mappen.

**Comment by abilustue** [comment]
Habe es installiert, müsste jetzt gehen
