### ISSUE TITLE
Entfernen von Geschäft-Vorlage aus Artikeln

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#37]
[Liste der Artikel die die `Geschäft`-Vorlage verwenden](https://www.tuepedia.de/htmltags-checker.php?v=%7B%7BGesch%C3%A4ft%20)

**Comment by dktue** [comment]
📉 **59**

**Comment by dktue** [comment]
📉 **40**

**Comment by Till-Kopper** [comment]
25

**Comment by Till-Kopper** [comment]
10

**Comment by dktue** [comment]
📉 **7**

**Comment by Till-Kopper** [comment]
1

Und das bekomme ich nicht gänzlich gelöscht.
