### ISSUE TITLE
Entfernen von Geschäft2-Vorlage aus Artikeln

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#38]
[Liste der Artikel die die `Geschäft2`-Vorlage verwenden](https://www.tuepedia.de/htmltags-checker.php?v=%7B%7BGesch%C3%A4ft2)

**Comment by dktue** [comment]
📉 **24**

**Comment by dktue** [comment]
📉 **4**

**Comment by Till-Kopper** [comment]
0
