### ISSUE TITLE
Extensions-Check

### ISSUE THREAD

**Issue by abilustue** [Tuepedia/Skinopt#4]
Bei den extensions habe ich einmal die bestehenden geprüft und geschaut, welche überhaupt noch aktiv sind und benutzt werden. Die anderen sind im Ordner "alte extensions" gelandet. 
Ebenfalls überarbeitet habe ich die Einbindung in der localsettings.php, geordnet nach Methode der Einbindung wf / require.

**Comment by abilustue** [comment]
Habe die Extension DynamicPAgeLists (Wikimedia) installiert, um nützliche Listen von kategorisierten Artikeln generieren zu können, zb für die neue Startseite (Artikel bei denen Bilder fehlen etc.) - 
Info: https://www.mediawiki.org/wiki/Extension:DynamicPageList_(Wikimedia)

**Comment by dktue** [comment]
Ist dieses Ticket noch aktuell?

**Comment by abilustue** [comment]
ist vielleicht zu allgemein ...
