### ISSUE TITLE
Bilder für Läden

### ISSUE THREAD

**Issue by abilustue** [Tuepedia/Skinopt#43]
Hallo, sehe ich es richtig, dass bei den neuen Vorlagen mit OSM die Bilder für Läden in WikimediaCommons sein müssen, um angezeigt zu werden? 
Wenn ja, fände ich es insgesamt schöner, wenn es ein sowohl als auch gäbe, also Tüpedia-Bilder da auch neben Commons-Bildern eingebunden werden können.

**Comment by dktue** [comment]
Die Vorlage nutzt einfach den Code `[[Datei:{{{image}}}|400px]]` -- es ist also durchaus möglich, auch ein TÜpedia-Bild dort einzubinden.

Allerdings würde ich davon abraten, in OSM einen TÜpedia-Dateinamen anzugeben, da nicht klar ist, aus welchem Stadtwiki die Datei geholt werden soll.

Alternativ wäre es möglich einen Tag `image` in OSM zu setzen und dort die vollständige URL zum Bild (in TÜpedia) einzutragen.

**Comment by abilustue** [comment]
Würde das so aussehen: image=https://www.tuepedia.de/'genauer pfad zur bilddatei.jpg'
?

**Comment by dktue** [comment]
Ganz genau.

Sobald Du einen Eintrag in OpenStreetMap gemacht hast würde ich die Vorlage anpassen, sodass ebendieses Bild genommen wird, sofern kein wikimedia_commons-Tag gesetzt wurde.

**Comment by abilustue** [comment]
ich hab es probiert: https://www.tuepedia.de/wiki/Zwergenreich
Bild: https://www.tuepedia.de/images/thumb/3/37/Laden_Zwergenreich_Tuebingen.jpeg/1280px-Laden_Zwergenreich_Tuebingen.jpeg

**Comment by dktue** [comment]
won't fix
