### ISSUE TITLE
Entfernen von googlemap-Vorlage aus Artikeln

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#46]
[Liste der Artikel die die `goolemap`-Vorlage verwenden](https://www.tuepedia.de/htmltags-checker.php?v=%3Cgoogle)

**Comment by dktue** [comment]
:chart_with_downwards_trend: **202**

**Comment by dktue** [comment]
📉 **98**

**Comment by dktue** [comment]
📉 **45**

**Comment by dktue** [comment]
Die Vorlage `googlemap` wurde aus allen Artikeln entfernt.

**Comment by Till-Kopper** [comment]
Bis auf "Benutzer:Cspan64/BaustelleABoGa" alle geändert. Da die Baustelle des Nutzers bereits in einen Artikel überführt ("Bäume im Alten Botanischen Garten") und auf die neue Kartensyntax umgestellt ist, ändere ich diese Benutzerseite nicht.
