### ISSUE TITLE
Bilder wo möglich auf Standardgröße setzen

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#47]
Werden bei Bildern keine explizite Position und Größe angegeben, so kann diese zentral beeinflusst und an das Aussehen der TÜpedia angepasst werden.

Wo von der Formatierung her Möglich sollte daher beispielsweise anstelle von

`[[Bild:Mein-Foto.jpg|thumb|right|300px|Bildunterschrift]]`

besser

`[[Bild:Mein-Foto.jpg|mini|Bildunterschrift]]`

genutzt werden.

**Comment by dktue** [comment]
[Diese Liste](https://www.tuepedia.de/htmltags-checker.php?v=px|) zeigt alle Artikel in denen explizite Größenangaben verwendet werden.

**Comment by Till-Kopper** [comment]
Jetzt werden nur noch 32 Stück in der [Liste](https://www.tuepedia.de/htmltags-checker.php?v=px%7C) anzeigt. Die sind wohl nicht einfach durch "mini" umzubauen.
