### ISSUE TITLE
Doppeltes Padding auf mobilen Geräten entfernen (chameleon Skin)

### ISSUE THREAD

**Issue by buckalot** [Tuepedia/Skinopt#48]
Vorschlag für die mobile Ansicht den doppelten Rand zu reduzieren:

z.b. in der custom.css Zeile 317 das Padding auf 0 stellen:
```
@media all and (max-width: 768px) {
    .detail-table {
        margin-left: 0;
        width: 100%;
    }
    .skin-chameleon #content {
        padding: 0;
    }
}
```

**Comment by dktue** [comment]
Ich habe es übernommen, das Padding allerdings auf 1em gesetzt anstelle von 0, da sonst die Buchstaben direkt am Rand des Bildschirms waren und beispielsweise der senkrechte Strich des Buchstabens L mit dem schwarzen Rand des Bildschirms verschmilzt.
