### ISSUE TITLE
Bilder aus commons in OSM Tabelle ergänzen funktioniert nicht 

### ISSUE THREAD

**Issue by fab-han** [Tuepedia/Skinopt#49]
Ich habe es vier Mal versucht, bei Art 28 ein commonsbild einzubauen, aber es kam immer eine böse Fehlermeldung 
![Screenshot_20220327-183019_Chrome](https://user-images.githubusercontent.com/5301663/160291598-86f1e8d7-3296-46ca-a416-958abb48301d.jpg)

**Comment by dktue** [comment]
Wie hast Du versucht das Bild einzubinden?

**Comment by fab-han** [comment]
Mit File:File Name - ich habe es in commons hochgeladen.

**Comment by Till-Kopper** [comment]
Sehe kein Problem. Es war nur bisher nicht alles am richtigen Platz.

Also auf OSM war bei Art28 kein wikimedia_commans drin. Das Foto heißt bei https://commans.wikimedia.org „Art28tuebingen.jpg“.
Habe also auf OSM bei Art 28 unter Eigenschaften „wikimedia_commans“ den Wert „File:Art28tuebingen.jpg“ eingetragen und den Edit auf OSM gespeichert.
Nun einfach den Server Cache des Art 28 Artikels auf TÜpedia gelöscht (URL des Artikel mit hinten angefügten „?action=purge“ aufgerufen und dann OK auf der erscheinenden Meldung klicken).
Und nun ist das Bild aus Wikimedia Commans via OSM im Infokasten auf TÜpedia.

Ich glaube, dass hier alles funktioniert.
