### ISSUE TITLE
HTML-Markup entfernen

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#6]
Um eine Skin-unabhängige und auch responsive-Design-taugliche Darstellung zu gewählrleisten sollte ausschließlich auf getestete Vorlagen und Wiki-Markup gesetzt werden. Sämtliches HTML sollte aus den Artikeln entfernt werden.

**Comment by dktue** [comment]
@buckalot : Kannst Du eine Kategorie für die Seiten erstellen, die HTML verwenden? So können wir das HTML zumindest bei den am häufigsten aufgerufenen Seiten herausoperieren.

**Comment by abilustue** [comment]
Gilt das auch für die Vorlagen? Und die Portale?

**Comment by dktue** [comment]
@abilustue : Ich denke Vorlagen dürfen HTML enthalten. Die Portale aber sollten nur Vorlagen verwenden und keinen HTML-Code.

**Comment by abilustue** [comment]
Vielleicht könntest Du @dktue Dir mal die Portale anschauen, da kann man sicher Vorlagen draus basteln, einige sind vom Dresdner Stadtwiki inspiriert, vielleicht findet man dort schon entsprechendes,

**Comment by buckalot** [comment]
Ich hab eine Liste aller Artikel/Seiten, die <div oder <table enthalten erstellt.
[div-table.pdf](https://github.com/Tuepedia/Skinopt/files/2415404/div-table.pdf)

**Comment by buckalot** [comment]
https://www.tuepedia.de/htmltags-checker.php?v=html
