### ISSUE TITLE
Google-Maps-Einbettung funktioniert nicht immer

### ISSUE THREAD

**Issue by dktue** [Tuepedia/Skinopt#7]
Mindestens beim Artikel der [Regionalstadtbahn](https://www.tuepedia.de/wiki/Regionalstadtbahn) wird ein Fehler angezeigt.

**Comment by Till-Kopper** [comment]
Bei der Regionalbahn ist auch die alte Syntax verwendet worden. Liegt sicher daran. Die wird ja nicht mehr unterstützt.
Da schaue ich bei Gelegenheit mal nach dem Umsetzen in die neue Syntax. Allerdings muss ich da erst mal schauen, wie ich die verschiedenen Liniefarben dort hinbekomme.

**Comment by Till-Kopper** [comment]
Ich habe die Karte des Regionalstadtbahn-Artikels nun auf die neue Syntax umgestellt (nun weiß ich wie Linien gehen). Nun funktioniert die wieder.

Wo klemmt es noch bei Karten?

**Comment by dktue** [comment]
Vielleicht können @abilustue oder @buckalot eine Liste aller Seiten mit alter Syntax erstellen die geprüft werden kann.

**Comment by abilustue** [comment]
Das müsste eigentlich über die Volltextsuche nach <googlemap funktionieren, da die Liste der betroffenen Artikel zu bekommen.

**Comment by buckalot** [comment]
Hey, ich hab ein PDF mit allen URLs, die das Wort "<googlemaps" enthält erstellt. Zusammen mit der Anzahl der Page-Views, damit man etwas priorisieren kann.
[googlemaps-tags.pdf](https://github.com/Tuepedia/Skinopt/files/2415229/googlemaps-tags.pdf)

**Comment by Till-Kopper** [comment]
Hallo Christian,

auf der Liste ist u.a. Schloss Hohentübingen. Dort gibt es kein “<googlemaps” aber “googlemaps”. Letzteres ist für die neue, funktionierende Kartensyntax notwendig und funktioniert.

Grüße 

    Till Kopper

**Comment by buckalot** [comment]
2. Versuch ...
[googlemaps-tags2.pdf](https://github.com/Tuepedia/Skinopt/files/2415307/googlemaps-tags2.pdf)

**Comment by buckalot** [comment]
Gerne. Gibt es jetzt auch immer top aktuell: https://www.tuepedia.de/htmltags-checker.php?v=googlemaps

**Comment by dktue** [comment]
Über `Geschaeft3` kann jetzt auch eine Karte eingebettet werden, siehe auch #12.

**Comment by dktue** [comment]
@buckalot : Kannst Du diese Auswertung eventuell so gestalten, dass wir nach Vorlagen suchen können? Konkret würde ich gerne wissen, welche Seiten noch `Geschäft` und `Geschäft2` verwenden.

**Comment by buckalot** [comment]
Jo: jetzt kann man über die URL den Suchterm ändern: https://www.tuepedia.de/htmltags-checker.php?v=Gesch%C3%A4ft2

**Comment by dktue** [comment]
Für die Vorlage `Geschäft` kann man folgende URL verwenden:
https://www.tuepedia.de/htmltags-checker.php?v={{Gesch%C3%A4ft%20

**Comment by dktue** [comment]
Gibt es noch Seiten auf denen es nicht funktioniert?

**Comment by dktue** [comment]
Keine Rückmeldung, also vermutlich keine offensichtlichen Fehler mehr. Wird geschlossen.
