### ISSUE TITLE
Infobox Geschäft anpassen

### ISSUE THREAD

**Issue by abilustue** [Tuepedia/Skinopt#8]
bei den Infoboxen Geschäft und Geschäft 2 wird die Schrift ohne Padding und oben nicht mittig angezeigt, was nicht so schön ist.

**Comment by dktue** [comment]
Ich arbeite Gerade an _Geschäft3_ die Parameter-abwärts-kompatibel zu _Geschäft2_ ist. Sobald diese fertig ist, können wir die aktuelle _Geschäft2_ in "Geschäft2Alt" umbenennen und die neue in "Geschäft2".

Beispiel für _Geschäft3_ (unfertig): https://www.tuepedia.de/wiki/Tatami

**Comment by abilustue** [comment]
Ich werde bei Gelegenheit mal sie Search-Replace Extension einbauen, dann kann man ganz leicht Suche-Ersetz-Operationen machen um z.B. Vorlageneinbindungen zu ändern.

**Comment by buckalot** [comment]
Ich hab auch eine Liste aller Seiten erstellt, die entweder <div oder <table enthalten.
[div-table.pdf](https://github.com/Tuepedia/Skinopt/files/2415402/div-table.pdf)

**Comment by dktue** [comment]
Die Vorlage `Geschäft3` kann nun getestet werden.
